### ISSUE TITLE
Research Computer Vision library on the web

### ISSUE THREAD

**Issue by fayeli** [fayeli/biojs-vis-bonestagram#1]

**Comment by sacdallago** [comment]
https://trackingjs.com/docs.html#introduction

**Comment by sacdallago** [comment]
http://wesbos.com/demos/html5-face-detection/

**Comment by fayeli** [comment]
**headtrackr.js**:
Javascript library for headtracking via webcam. It uses a Viola-Jones type detector from ccv library to detect the faces, then implements Camshift algorithm to track the object based on colour histogram.
https://github.com/auduno/headtrackr
Details: http://auduno.com/post/25125149521/head-tracking-with-webrtc

**Comment by fayeli** [comment]
**JSfeat**:
A Javascript library with implementations of many directly relevant image processing or computer vision algorithms, such as feature detection or pre-trained face detectors, which can help finding where the user is on the webcam. It also has geometric transformations (e.g. homography, affine) which we can use for mapping a DICOM image.
http://inspirit.github.io/jsfeat/

**Comment by fayeli** [comment]
**clmtrackr**:
A Javascript library for fitting facial models to faces in videos or images. It requires JSfeat for initial face detection, and provides the fitted facial model which can allow for more accurate mapping than simple overlaying images.
https://github.com/auduno/clmtrackr
Demo: https://auduno.github.io/clmtrackr/face_mask.html

**Comment by fayeli** [comment]
**node-opencv**:
NodeJS binding for opencv. Should support all the computer vision features of opencv, such as the Viola-Jones face detector and others relevant functions.
https://www.npmjs.com/package/opencv
Tutorial: https://www.sitepoint.com/face-detection-nodejs-opencv/

**Comment by fayeli** [comment]
**js-objectdetect**:
Javascript library implementing Viola-Jones for object detection
https://github.com/mtschirs/js-objectdetect

**Comment by fayeli** [comment]
**ccv**:
Javascript library implementing many computer vision algorithms
https://github.com/liuliu/ccv
