### ISSUE TITLE
Web App with good UI

### ISSUE THREAD

**Issue by fayeli** [fayeli/biojs-vis-bonestagram#12]
Design a web app that will be the main page of Bonestagram.

It should have:
- simple, easy to use user interface
- description of project and its cause
- bonestagram.js documentation & usage example
- social plugins (facebook share etc.)

**Comment by fayeli** [comment]
Logo First Draft:
![logo](https://cloud.githubusercontent.com/assets/2405697/16754614/0afd746e-47a9-11e6-91d4-74258acd5c52.png)

Just trying to keep it simple & clean with two tone colors. Inputs are welcome! (: @hesamrabeti @sacdallago

**Comment by sacdallago** [comment]
Nice logo :)
Why the choice of a non-perfectly circular form? I am curious :)
My observations are:
- The deformed shape is not deformed enough in my opinion
- Have you considered shaping the oval in the form of some bone? Or give it an x-ray like feel?

Keep the good work up :)

**Comment by sacdallago** [comment]
So, again for the points discussed today, in my opinion it would be nice to have:
- A clear understanding that users can upload their own scans / upload button
- A "disclaimer" page, where you explain that the scans are not really going to be uploaded but are rather serviced directly from within the browser
- An "about" page where you talk about yourself, the context in which this project was born, if you had fun doing it :)
- A "docs" page where you give hints on to how to use the package and where to get it from (docs pages have a pretty "standard" format, eg. http://docs.meteor.com/api/connections.html or http://semantic-ui.com/modules/modal.html --> code example -> explanation what's happening -> options)
- A nice an big "download" button that brings you to the GitHub repository.

Concerting the hosting: GitHub allows you to create a "github page" for your repository. This will create a branch called `gh-pages` where the content of that branch is serviced at githubuser.github.io/nameofrepo

An example for this is here:
https://github.com/Rostlab/JS16_ProjectC_Group10

when you open that link you are on the `develop` branch. You can then switch to the `gh-pages` branch and will notice that on the root you have the `index.html`. This is what will be serviced when connecting to http://rostlab.github.io/JS16_ProjectC_Group10
