### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by sacdallago** [fayeli/biojs-vis-bonestagram#22]
Here is schematic example of folder structure for these kinds of projects (note that I took a few of the filenames from the actual code, to help you understand what goes where):

``` bash
bonestagram/
├── bin
│   └── index.js
├── example
│   ├── app.js
│   ├── index.html
│   └── styles
│       └── style.css
├── license.md
├── package.json
├── readme.md
└── src
    ├── bonestagram.js
    └── lib
        ├── component.js
        └── require.js
```
1. Notice that the 'bonestagram/' folder in this case would be the root of the repository.
2. In the app.js of the example, you would require bonestagram like: `/../src/bonestagram.js` the `..` notation means that you are going one folder back.

Hit me up if anything is unclear!

**Comment by fayeli** [comment]
Hi @sacdallago !

I was just using the generator tool from Biojs (http://edu.biojs.net/101/bootstrapping/) to create the directory structure. It gave me this, which is quite similar to your schematic:
![screen shot 2016-08-09 at 3 59 00 pm](https://cloud.githubusercontent.com/assets/2405697/17536547/91b00154-5e4a-11e6-9162-d3c796ffb2d6.png)
It doesn't have a ./src folder. would it be okay if I just create one and put my raw source over there?

Also, the guide recommends to use a BioJS standard name for the package (in our case, biojs-vis-bonestagram). The generator assumes the github to be the same name too, so I pushed the whole folder up here at https://github.com/fayeli/biojs-vis-bonestagram 

I'm a bit confused on how to format our bundled code ./bin/bonestagram.bundle.js for the ./lib/index.js over there.

Would you mind taking a look at it?

**Comment by sacdallago** [comment]
Hi @fayeli 
Good work! They really have started putting some more effort in standardizing biojs packages. The folder structure is pretty standard, so I am not surprised that it is similar :) It is very much ok for you to have the src folder, it is actually needed to understand the code!

You can also rename a repository on github, and I would actually prefer if you did that (just go into the settings of the repo). So: delete the one that you just created and rename this one to the approved name `biojs-vis-bonestagram`. I say so, because this repo has issues and commits associated, and while you could theoretically clone the git history, you cannot do so for the issues history!

I will take a look at the bundle problem later today :)

**Comment by sacdallago** [comment]
P.S.: if the code on https://github.com/fayeli/biojs-vis-bonestagram is already in it's pre-final stage and more recent than the code in the `bonestagram` repo, then just delete all of the contents in the `bonestagram` repo (except the .git hidden folder) and replace it with the contents of the `biojs-vis-bonestagram` folder (except .git folder). It's a little hack :) But it will do the job!
