### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by mohtamohit** [fayeli/biojs-vis-bonestagram#24]
Demo at bonestagram.com isn't opening for me. There are some redirects, probably it fells into a never ending loop of redirects like from a to b and then back from b to a and so on.

**Comment by sacdallago** [comment]
Hi @mohtamohit thanks for the heads up and sorry for the late reply. I am looking into it

**Comment by mohtamohit** [comment]
@sacdallago @fayeli   Welcome. Actually, I got to know about the organization while I was searching for a GSoC project for summer job. Sir, I would be glad to contribute for this project this summer. Can you help me in getting started and through making a good proposal?

**Comment by mohtamohit** [comment]
@sacdallago  And, have they applied to appear back in GSoC 2017?

**Comment by fayeli** [comment]
Hi @mohtamohit, thanks for your interest to this project! I'm not sure if it will be appear back in GSoC 2017. Perhaps you might find answers from the organisers over at the BioJS slack channel. 

As for the broken link, @sacdallago owns the domain name and it looks like something was up with the hosting. We'll try to fix that soon. In the mean time, if you'd like to try out the demo, feel free to clone this repo and run it locally. Alternatively we also have this video demo: https://www.youtube.com/watch?v=uWDkqoFHr_g

Hope this helps!

**Comment by sacdallago** [comment]
I have opened a ticket a month ago on the hosting service where the website is hosted. They still haven't been able to fix the problem, sorry!

There isn't much else I can do, as the problem depends from them :(

We are not going to apply for this year, unfortunately we don't have enough people and time to put into it! But I encourage you to look around at other orgs, some have similar interests :)

**Comment by fayeli** [comment]
Aww I see. Maybe I'll look into hosting it on like heroku or something for the mean time (:

**Comment by fayeli** [comment]
Just got it up and running on http://bonestagram.herokuapp.com/ Not as nice as our custom domain, but at least the demo is up! (:

**Comment by sacdallago** [comment]
Thanks @fayeli . I am still waiting (and paying) for the domain. Last resort might be to transfer it.

**Comment by mohtamohit** [comment]
@fayeli @sacdallago It's really good. Just checked it out. :+1:
