### ISSUE TITLE
General

### ISSUE THREAD

**Issue by sacdallago** [fayeli/biojs-vis-bonestagram#3]
Hi @fayeli ,

would it be OK to hold a meeting coming Wednesday at 2 CEST? So you can tell us what were the results of the first week of research, and what you are doing in the second week.

CC @hesamrabeti

**Comment by fayeli** [comment]
Hi @sacadallago,

I'll need to get back to you later about that. I'm currently driving across the country, moving from Indiana to California. Depending on how far we get, we might be changing time zone and that might be 6 or 7 am over here. I should be at a hotel with internet connection but I'll confirm with you again the night before!

Cheers,
Faye

CC @hesamrabeti

**Comment by fayeli** [comment]
Hi @sacdallago,

I'll need to get back to you later about that. I'm currently driving across the country, moving from Indiana to California. Depending on how far we get, we might be changing time zone and that might be 6 or 7 am over here. I should be at a hotel with internet connection but I'll confirm with you again the night before!

Cheers,
Faye

CC @hesamrabeti

**Comment by sacdallago** [comment]
Maybe you can do 4pm CEST? I won't be available then, but @hesamrabeti should.

**Comment by sacdallago** [comment]
Hi @fayeli ,

when would you like to hold the meeting coming Wednesday?

**Comment by fayeli** [comment]
Hi Chris,

Would 9 am cest be good? I'm now in Pacific time zone and that'd be midnight Tuesday for me. I figure earlier might be better than afternoon when it's 5 or 6 am for me. What do you think?

Cc@hesamrabeti

**Comment by sacdallago** [comment]
9AM CEST works for me.
@hesamrabeti ?

**Comment by hesamrabeti** [comment]
Works for me also.
