### ISSUE TITLE
Segmentation of medical images

### ISSUE THREAD

**Issue by sacdallago** [fayeli/biojs-vis-bonestagram#7]
- [x] Ask Jan about medical images segmentation

**Comment by jankukacka** [comment]
Hey, I'm not using JS for my project, so I don't know any JS libraries for the purpose. In general, accurate bone segmentation from various images is not that trivial, but I guess for this project you don't need 100% accurate results.

For CT images, you should get normalized values in Hounsfield units. Every tissue has specific range, so it might be possible to filter out most of the background etc. just by thresholding of the bone range.

For MRI images, it is a much more complicated...

**Comment by fayeli** [comment]
Thanks for the great input, Jan! I'll look into that.
